name = "glatus"
version = "2.0.0"

description = "Gleam bindings to the API of the Gatus health check tool"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "glatus" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.51.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 3.0.0"
gleam_http = ">= 3.0.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_httpc = ">= 4.0.0 and < 5.0.0"
