name = "glatus"
version = "1.0.0"

description = "Gleam bindings to the API of the Gatus health check tool"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "glatus" }
links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.32"
gleam_json = "~> 0.7"
gleam_http = "~> 3.5"

[dev-dependencies]
gleeunit = "~> 1.0"
simplifile = "~> 0.2"
gleam_httpc = "~> 2.1"
